# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
