# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisment', '0002_auto_20170811_0559'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
